version: '3.1'

services:
  mariadb:
    image: mariadb:10.6.7
    environment:
      MYSQL_DATABASE: tecweb
    volumes:
      - ./_database/database.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Add the following lines to set the user and group for the Apache process
    user: "${UID}:${GID}"
    environment:
      UID: "${UID}"
      GID: "${GID}"
    depends_on:
      - mariadb
    command: php -S 0.0.0.0:80 -t /var/www/html
